### ISSUE TITLE
Improve DX by showing the PX equivalent for the REM values

### ISSUE THREAD

**Issue by guilhermefront** [Mokshit06/typewind#14]
### Describe the feature you'd like to request
Show the equivalent of the rem value in PX on the typings. This is useful because usually the layout token values are given in PX instead of rem.
How it is currently:
![image](https://user-images.githubusercontent.com/49620737/215338498-68e44325-1d2f-4292-b5fc-13d1bb1a7221.png)

### Describe the solution you'd like
Something like the tailwind intellisense already does would be great (see the // 16px)
![image](https://user-images.githubusercontent.com/49620737/215338031-0418bad4-15ca-4a4d-8f44-822b6f28dbe4.png)

**Comment by kavinvalli** [comment]
Should now work with https://github.com/Mokshit06/typewind/commit/627eab2669adb012597dfcc22fc9e8354538e33f. You will have to create a typewind config file for this. Will add this to the docs ASAP.

**Comment by Mokshit06** [comment]
This has been added in `v0.0.9`. You need to add the following to your `package.json` and run `npx typewind generate`:
```json
{
  "typewind": {
    "showPixelEquivalents": true
  }
}
```

<img width="650" alt="Screenshot 2023-02-02 at 12 37 32 PM" src="https://user-images.githubusercontent.com/50412128/216255509-f9df7896-3b71-44f1-93b2-b01483e36465.png">
