### ISSUE TITLE
Multiple Tailwind configs in one project

### ISSUE THREAD

**Issue by wilsonlewis** [Mokshit06/typewind#18]
Would this package unlock the ability to have multiple tailwind configs in one project?

For example, we have our site's brand, but in some areas we require custom branding from our clients (including different spacing, fonts, colors, etc.). We didn't want to pollute our branding/design system with our clients, so we just use arbitrary values for everything within that scope, which can be annoying and inconsistent

As far as I know, the reason you can't have multiple tailwind configs right now is because editors don't understand context. But, would using an explicit import like typewind solve that problem?

Anyway, just a thought...

Thanks

**Comment by kavinvalli** [comment]
I think this is possible in tailwind now: https://tailwindcss.com/blog/tailwindcss-v3-2#multiple-config-files-in-one-project-using-config.

At the moment, this will be a little hard to implement with Typewind since we compile the types from `typewind generate` based on one `tailwind.config.(c)js` which is either in the root of the project or set as [Custom Config](https://typewind.vercel.app/docs/setup/custom-config-file-path). So, the one thing I can think about right now, is while working on a particular section, generate types for that section and then while switching back change the custom config file path and generate types again using `typewind generate`.

**Comment by kavinvalli** [comment]
@Mokshit06 Any views on this, or I think we can close his issue.

**Comment by wilsonlewis** [comment]
@kavinvalli thanks for the response!

The example tailwind docs makes sense for having difference contexts of project (ie. admin vs client). But, does it work for difference systems in the same context?

Do you know if having the two configs are merged into a single autocomplete system in terms of your editor? If I have `text-grey-2` in both systems, how does it know what to hint? Or, if I have `text-alert` in one system, but not the other, will it still show up in autocomplete in a context that does not support utility?

Anyway, these are the problems I was hoping to solve

Sort of like how we started using modules instead of globals to prevent naming collisions in the first place 😉

**Comment by kavinvalli** [comment]
@wilsonlewis, the two configs won't be merged into one autocomplete system in Typewind, like I mentioned above. The types are generated with `npx typewind generate` based on a particular config which is either in the root of the directory, or as mapped as [Custom Config](https://typewind.vercel.app/docs/setup/custom-config-file-path) in the package.json. So, if you want to work on a particular autocomplete system, set that as the tailwind config, run `npx typewind generate` and then work on that. When you want to work on the other, change the custom tailwind config, and then run `npx typewind generate` again.

**Comment by Mokshit06** [comment]
Hey! so this is possible if you give both the project dirs a separate `package.json` and a separate install of typewind. The way typewind's autocomplete works is that it generates a `index.d.ts` file in the `node_modules/typewind` directory, so if you want separate autocomplete, you would require 2 different `index.d.ts` file being generated, and 2 different installations. 
This doesn't need to interfere with the rest of your package dependencies.

It would like like:

- root dir
  - node_modules/typewind
  - tailwind.config.js 
  - src/* - All files here have access to theme from the file above
  - client
    - tailwind.config.js
    - node_modules/typewind
    - *.ts - All files here only have access to theme from client/tailwind.config.js
