### ISSUE TITLE
Babel dependency

### ISSUE THREAD

**Issue by minsour** [Mokshit06/typewind#19]
Are there any plans to remove the dependency on babel in the future?

As typewind depends on babel, I need to create a .babelrc in nextjs project.
For this reason, from nextjs v12 and later versions, the build time increases by using webpack instead of swc when building.

**Comment by Bluzzi** [comment]
#15

**Comment by kavinvalli** [comment]
Yes, this has been answered by #15. If you have any other question related to this, feel free to reopen the issue.
