### ISSUE TITLE
Does Typewind support arbitrary variants?

### ISSUE THREAD

**Issue by sentience** [Mokshit06/typewind#2]
[Arbitrary variants](https://tailwindcss.com/blog/tailwindcss-v3-1) were added in Tailwind 3.1. Does Typewind support this yet?

**Comment by kavinvalli** [comment]
This should be doable. Will give this a try today.
@Mokshit06

**Comment by kavinvalli** [comment]
https://github.com/mokshit06/typewind/commit/755506ddcd1ab6d5ab9cf3c5154c6fadce5 should work!

@Mokshit06 will release the new version soon!

**Comment by kavinvalli** [comment]
@sentience The syntax has been changed as indicated [here](https://typewind.vercel.app/docs/usage/arbitrary-variants) because the old syntax was giving an issue with the typescript messages and wasn't very clear as to the errors.
