### ISSUE TITLE
add support for ts config files

### ISSUE THREAD

**Issue by sigmachirality** [Mokshit06/typewind#22]
`typewind generate` fails when the tailwind config is a typescript file instead of a cjs file. Is there any way we can get support for writing the tailwind file as a cjs file, or does tailwind require specific behavior from cjs/require import syntax module loading?

Same issue with postcss.config.cjs.

**Comment by Mokshit06** [comment]
Tailwind requires the config file to either be `tailwind.config.js` or `tailwind.config.cjs` and can't import a ts config file.

TS also doesn't have much advantage in the config as you already get autocompletion in js with jsdoc
