### ISSUE TITLE
populate the engines field in the package.json

### ISSUE THREAD

**Issue by sigmachirality** [Mokshit06/typewind#23]
I'm following along with the vite example to convert an existing vite repo. When I installed typewind with node 14, the following occurred when I tried to run `yarn dev`: 

```
bug: Unexpected token '??=' (While processing: .../node_modules/typewind/dist/babel.js)
```

I was able to fix this by bumping my node from 14 to 18 using `n`. Can you spend some time testing which node major versions work with typewind and specify the supported versions using the `engine` field in the package.json? 

https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines

**Comment by kavinvalli** [comment]
Will look into this today. Thanks for telling!

**Comment by kavinvalli** [comment]
Closed by mistake. My bad

**Comment by kavinvalli** [comment]
@sigmachirality Added: https://github.com/Mokshit06/typewind/blob/c2d6019cc984a251e6534425424f892d81b4fa52/package.json#L5-L7

**Comment by kavinvalli** [comment]
Sorry for the delay!

**Comment by sigmachirality** [comment]
Thanks for the fix!
