### ISSUE TITLE
add support for daisyui and other tailwind-based component libraries

### ISSUE THREAD

**Issue by sigmachirality** [Mokshit06/typewind#24]
bit of a pie in the sky idea, but it would be nice if typewind could parse classes from other tailwind plugins - currently adding daisyui to my plugins breaks typewind's type codegen, resulting in the tw import being typed as `unknown`

**Comment by kavinvalli** [comment]
This did work with plugins like `tailwindcss-animate` and `@tailwindcss/typography`. I'll take a look at this.

**Comment by kavinvalli** [comment]
![Screenshot 2023-02-01 at 18 09 06](https://user-images.githubusercontent.com/41034356/216044770-9da34cd4-bf9a-4a2b-a17d-48fb3a7caebc.png)
Seems to be working for me @sigmachirality. Did you run `npx typewind generate` after adding daisyui to the plugin list?

**Comment by kavinvalli** [comment]
@sigmachirality I can't seem to be able to reproduce this issue. Can you give us a few more details?

**Comment by sigmachirality** [comment]
I'll look into it again on my end. Thanks for the prompt response!

**Comment by sigmachirality** [comment]
There was issue with my language server on my end, closing this issue!
