### ISSUE TITLE
SWC plugin support

### ISSUE THREAD

**Issue by popuguytheparrot** [Mokshit06/typewind#30]
This is an issue as a start for RFC to develop a swc plugin instead of babel plugin

**Comment by kavinvalli** [comment]
Hi! This has been answered [here](https://github.com/Mokshit06/typewind/issues/15#issuecomment-1407744534).

**Comment by kavinvalli** [comment]
Hi! We've actually added it now: https://typewind.vercel.app/docs/transpilers/swc
