### ISSUE TITLE
Typewind generates unescaped * className causing ts language server parsing errors

### ISSUE THREAD

**Issue by sigmachirality** [Mokshit06/typewind#34]
Figured out why I was having this issue: https://github.com/Mokshit06/typewind/issues/24 - while some DaisyUI classes were properly typed, others weren't, and the ones that were and weren't were arbitrary.

Turns out in the generated file, it produced the following `Property`

<img width="598" alt="Screen Shot 2023-02-25 at 6 53 05 PM" src="https://user-images.githubusercontent.com/2645695/221384918-0c02551d-dfe2-401c-94c9-e8e5a89bc1dc.png">

As a result, all classes generated on lines after this one (such as `hero-content`) are broken. If this `Property` is escaped as follows:

<img width="391" alt="Screen Shot 2023-02-25 at 6 55 17 PM" src="https://user-images.githubusercontent.com/2645695/221384967-d46c6e44-56df-4ec1-9c70-80340dd9c0bf.png">

The exported `tw` object typechecks with all members correctly. If you could look into pushing a hotfix to a.) escape this class as shown b.) remove the class c.) investigate whether this class is getting generated correctly (maybe it's supposed to be something else?) that would be great! I'm looking to use this library in production more but missing most of the classes from the `tw` object/having to monkey patch the export is far from ideal.

**Comment by kavinvalli** [comment]
@sigmachirality Is this happening in the latest version. We have actually fixed this issue before as well in https://github.com/Mokshit06/typewind/issues/9, but I'll take a look again: https://github.com/Mokshit06/typewind/commit/56429a6809fefe35cb0f93087ae6e0685a4214ce

**Comment by sigmachirality** [comment]
I bumped my version and it fixed it! My bad.
