### ISSUE TITLE
Arbitrary Values Not Supported in Plugins When Using SWC

### ISSUE THREAD

**Issue by mutewinter** [Mokshit06/typewind#37]
I have a custom Tailwind plugin defined as follows:

```javascript
const sizePlugin = plugin(({ matchUtilities, theme }) => {
  matchUtilities(
    {
      s: (value) => {
        let [width, height] = Array.isArray(value) ? value : [value, value];
        return { width, height };
      },
    },
    {
      values: {
        auto: 'auto',
        ...theme('spacing'),
        '1/2': '50%',
        '1/3': '33.333333%',
        '2/3': '66.666667%',
        '1/4': '25%',
        '2/4': '50%',
        '3/4': '75%',
        '1/5': '20%',
        '2/5': '40%',
        '3/5': '60%',
        '4/5': '80%',
        '1/6': '16.666667%',
        '2/6': '33.333333%',
        '3/6': '50%',
        '4/6': '66.666667%',
        '5/6': '83.333333%',
        full: '100%',
        screen: ['100vw', '100vh'],
        min: 'min-content',
        max: 'max-content',
        fit: 'fit-content',
      },
    },
  );
});
```

It works fine when used like so: `tw.s_4`. However it fails to emit classes when used like so: `tw.s_['10px']` or with a built-in variant `tw.s_['1/2']`.

The classes don't show up at all when using the bracket notation with this plugin.

A more simple version of the plugin **that also doesn't work** follows:

```javascript
const sizePlugin = plugin(function ({ matchUtilities, theme }) {
  matchUtilities(
    {
      s: (value) => ({
        width: value,
        height: value,
      }),
    },
    {
      values: theme('spacing'),
    },
  );
});
```

I'm using the latest version of Typewind, `0.1.1` with NextJS 13.2.3 and the SWC plugin.

**Comment by Mokshit06** [comment]
Hey, thanks for reporting. Is this using the swc plugin or Babel? It isn't possible to do this with the swc plugin unfortunately

**Comment by Mokshit06** [comment]
Hey, thanks for reporting. Unfortunately this isn't possible with the swc plugin as it can't read the tailwind config as it is compiled to wasm and doesn't have fs access

**Comment by mutewinter** [comment]
Ahh, gotcha. Didn't realize that. I'll switch to the Babel version for now. Might be worth a caveats section in the README / docs.

**Comment by Mokshit06** [comment]
I like this idea. Will add both soon

**Comment by kavinvalli** [comment]
Should be added in https://github.com/Mokshit06/typewind/commit/b8a77dd107b38636c25753bde0384fe2aa911671! @Mokshit06 will release it soon!
