### ISSUE TITLE
Is this package supposed to be "private'?

### ISSUE THREAD

**Issue by Samathingamajig** [Mokshit06/typewind#4]
In the `package.json` I see the following line:

https://github.com/Mokshit06/typewind/blob/81de675dfe481be8e27b723d0582308eec7c21a3/package.json#L4

Is it intentionally "private"? I'm not sure if that changes anything on the npm side. I know that originally this was a private repo, but it's public now and the docs talk about installation.

**Comment by Mokshit06** [comment]
Yes this root package is intentionally private. Typewind's repository is a monorepo so the root package.json is private, which only includes the workspace config, and the package published to npm is packages/typewind
