### ISSUE TITLE
Arbitrary groups feature request

### ISSUE THREAD

**Issue by epicbytes** [Mokshit06/typewind#45]
Hi @Mokshit06, what you think about support arbitrary group and another css/tw features in typewind?
I mean:
peer-[:nth-of-type(3)_&]:block
after:content-['*']
peer-checked/published:text-sky-500
[&_:where(th,td)]:p-2

and so on

**Comment by epicbytes** [comment]
So, in the source code I found a test with these cases except couple cases

**Comment by Mokshit06** [comment]
Typewind works for most of these where the syntax is easily transferable to Javascript equivalents. For more "crazy" combinations, I feel like using `tw.raw` is probably the best way to go
