### ISSUE TITLE
Error on NextJS 13.4.4, Filesystem cache is not enabled

### ISSUE THREAD

**Issue by heygema** [Mokshit06/typewind#47]
Hello, one error I encountered
is this after executing `pnpm dev`

```
error ./node_modules/next/dist/client/dev/amp-dev.js
Error: Filesystem cache is not enabled, cannot read plugin from phsyical path
- wait compiling...
- error ./node_modules/next/dist/client/dev/amp-dev.js
Error: Filesystem cache is not enabled, cannot read plugin from phsyical path
```

to reproduce :

create next project
```npx create-next-app@latest```
choose app dir, and yes to everything.

my config
```js
/** @type {import('next').NextConfig} */
const path = require('path');

const nextConfig = {
  reactStrictMode: true,
  webpack: (config, { isServer }) => {
    // This will replace the default entry point for the '@' symbol with the 'src' directory
    config.resolve.alias['@'] = isServer
      ? path.join(__dirname, './src')
      : path.join(process.cwd(), './src');
    return config;
  },
  experimental: {
    swcPlugins: [['typewind/swc', {}]],
  },
};

module.exports = nextConfig;
```

is there any way to enable this `filesystem cache` somehow we don't know about

thanks before

**Comment by indiejoseph** [comment]
Hi @heygema , have you figured it out?

**Comment by heygema** [comment]
> Hi @heygema , have you figured it out?

not yet, I carried on with the previous version of next. If you have reproduced it or solve it that would be helpful

**Comment by Mokshit06** [comment]
I believe this was also similar to other SWC errors that have been reported, which were caused due to incompatibility of the older swc_core used by typewind with the swc version used by Next.js. This should be fixed in the latest release.
