### ISSUE TITLE
Nextjs 13.4 SWC plugin not working with typewind

### ISSUE THREAD

**Issue by pawanrana1992** [Mokshit06/typewind#50]
### Discussed in https://github.com/Mokshit06/typewind/discussions/49

<div type='discussions-op-text'>

<sup>Originally posted by **pawanrana1992** July  7, 2023</sup>
I am trying to use Typewind in nextjs 13.4.x with SWC support, but it is not working as per the suggested configuration for swc from Typewind side. I am getting error like this. can anyone please suggest what is the right configuration for Nextjs 13.4. I love this plugin and any how I need to use it. please help.
<img width="1160" alt="Screenshot 2566-07-07 at 1 03 56 PM" src="https://github.com/Mokshit06/typewind/assets/41635595/96065668-091a-4e33-9f46-bab97b3f1b02">
<img width="809" alt="Screenshot 2566-07-07 at 1 04 16 PM" src="https://github.com/Mokshit06/typewind/assets/41635595/f88690f6-6b3a-406e-ad80-4d08a97e31a7">
<img width="1380" alt="Screenshot 2566-07-07 at 1 05 19 PM" src="https://github.com/Mokshit06/typewind/assets/41635595/591a4e8f-8ad6-4c42-8d55-d964ba2e8833">
</div>

Note: also if i am using typewind inside rollup lib, and after build and use inside nextjs project with babel. 
1. library build has reference to use custom config name like `my_colors_primary_main`. and not throw any error with rollup build. and storybook also works fine with custom colors.
2. typewind inside the library used as external dep
3. Nextjs setup with tailwind and typewind using babel to work. (`tw.my_colors_primary_main` works in the nextjs)
4. Added the tailwind theme config as per lib requirement
5. Generated the typewind config using `npx typewind generate`
6. Importing a component from library to nextjs project
7. the library throw error that `my_colors_primary_main` not found.

Please help how can i resolve this issue as well.

Thanks in advance team.

**Comment by Mokshit06** [comment]
I believe the latest release should fix this, sorry for the late response. Btw if the swc plugin throws any error later on due to compat reasons, you can always fall back to the babel plugin.
