### ISSUE TITLE
BUG: Typewind Generate command doesn't work

### ISSUE THREAD

**Issue by GhostCrawl3r** [Mokshit06/typewind#52]
Hey all,

I have just installed typewind for the first time and I have everything setup but I get an error running `pnpx typewind generate`. This is the error I get:

```
.../Library/pnpm/store/v3/tmp/dlx-33723  | Progress: resolved 187, reused 158, downloaded 1, added 159, done
node:internal/modules/cjs/loader:988
  throw err;
  ^

Error: Cannot find module 'tailwindcss/resolveConfig.js'
Require stack:
- /Users/X/Library/pnpm/store/v3/tmp/dlx-33723/node_modules/.pnpm/typewind@0.1.3/node_modules/typewind/dist/cli.js

```

I was curious and had a look at the file this calls: `node_modules/typewind/src/utils.ts` It shows an issue with the createContext import:
![Screenshot 2023-08-14 at 12 38 00](https://github.com/Mokshit06/typewind/assets/36843980/d9c03916-7f38-4dd1-8c79-756a5cea79a9)

Could anyone help me resolve this please?

**Comment by Mokshit06** [comment]
Hey! I wonder if you have tailwindcss installed in your project. Can you try running `npm install tailwindcss` and see if you still face this? This error doesn't seem related to typewind.
