### ISSUE TITLE
How can I repeat this entry using typewind

### ISSUE THREAD

**Issue by kravetsone** [Mokshit06/typewind#53]
How can I repeat this entry using typewind
it's custom color with opacity

![image](https://github.com/Mokshit06/typewind/assets/57632712/3f78463a-89e6-48b7-aa7b-2bb986ff20dd)

**Comment by Mokshit06** [comment]
Custom colours with opacity aren't currently supported by typewind's `tw.*` syntax. But I'm not sure what you mean by repeat. You could extract it out into a variable like

```js
const custom_gradient = tw.raw("from-[#1F0637]/70")
```

and later use that
```js
const style = `${custom_gradient} ${tw.bg_red}`
```
. If it's something else then feel free to comment here
